/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package template

import com.kotlindiscord.kord.extensions.ExtensibleBot
import com.kotlindiscord.kord.extensions.utils.env
import template.extensions.HSEExtension

private val TOKEN = env("TOKEN")   // Get the bot' token from the env vars or a .env file
    ?: error("Env var TOKEN not provided")

suspend fun main() {
    val bot = ExtensibleBot(TOKEN) {
        messageCommands {
            defaultPrefix = "?"
        }

        slashCommands {
            enabled = true
        }

        extensions {
            add(::HSEExtension)
        }

        presence {
            playing("/jabs")
        }
    }

    bot.start()
}
